name: build and push docker image

on:
  push:
    branches:
      - master
      - main

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.ORLEANS_REGISTRY_USERNAME}}
          password: ${{secrets.ORLEANS_REGISTRY_PASSWORD}}
          
      - name: build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Silo.Warehouse/Dockerfile
          push: true
           tags: |
            ${{secrets.ORLEANS_REGISTRY_USERNAME}}/silo-wh:latest
            ${{secrets.ORLEANS_REGISTRY_USERNAME}}/silo-wh:${{github.sha}}