name: build and push docker image

on:
  push:
    branches:
      - master
      - main

  # Allow manual trigger 
  workflow_dispatch:

env: 
  IMAGE_NAME: silo-wh

jobs:   
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.ORLEANS_REGISTRY_USERNAME}}
          password: ${{secrets.ORLEANS_REGISTRY_PASSWORD}}
          
      - name: build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Silo.Warehouse/Dockerfile
          push: true
          tags: |
            ${{secrets.ORLEANS_REGISTRY_USERNAME}}/${{env.IMAGE_NAME}}:${{github.run_number}}
            ${{secrets.ORLEANS_REGISTRY_USERNAME}}/${{env.IMAGE_NAME}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  redeploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: send webhook
        uses: fjogeleit/http-request-action@v1
        with: 
          url: ${{secrets.VM_WEBHOOK_URL}}
          method: 'POST'
          customHeaders: '{"content-type":"application/json","x-api-key":"${{secrets.VM_API_KEY}}"}'
          data: '{"image": "${{ secrets.ORLEANS_REGISTRY_USERNAME }}/${{env.IMAGE_NAME}}:${{ github.run_number }}", "action": "deploy"}'
          retry : 3
          retryWait: 10000